<?php
    session_start();
    include_once("_header.html");
    include_once("_navbar.html");
    include_once("_signin.html");
    include_once("_footer.html");
    if(isset($_POST["user"])){
        $_SESSION["user"]=$_POST["user"];
    }
?>