<?php
    session_start(); 
    if(isset($_POST["user"])){
        $_SESSION["user"]=$_POST["user"];
    }
    if(isset($_POST["passwrd"])){
        $_SESSION["passwrd"]=$_POST["passwrd"];
    }
    include_once("verifyAccount.php");
    if(veryAccount()&&veryPasswrd()){
        include_once("dashboard.php");
    }else{
        include_once("invalidUser.php");
    }    
?>